const path = require("path")

module.exports = {
  darkMode: "class",
  presets: [require("@medusajs/ui-preset")],
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/modules/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      transitionProperty: {
        width: "width margin",
        height: "height",
        bg: "background-color",
        display: "display opacity",
        visibility: "visibility",
        padding: "padding-top padding-right padding-bottom padding-left",
      },
      colors: {
        pcb: "#FFFFFF",
        surface: "#F5F6F7",
        raised: "#E5E7EB",
        ink: "#1A1A1A",
        muted: "#667085",
        copper: "#F97316",
        traceOk: "#1DAA5C",
        traceFail: "#E5342B",
        grey: {
          0: "#FFFFFF",
          5: "#F9FAFB",
          10: "#F3F4F6",
          20: "#E5E7EB",
          30: "#D1D5DB",
          40: "#9CA3AF",
          50: "#6B7280",
          60: "#4B5563",
          70: "#374151",
          80: "#1F2937",
          90: "#111827",
        },
        "on-tertiary-container": "#650d00",
        "surface-container-lowest": "#ffffff",
        primary: "#a14000",
        "error-container": "#ffdad6",
        "secondary-container": "#e4e2e1",
        "inverse-surface": "#2f3131",
        "on-primary-fixed": "#351000",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed-variant": "#8d1700",
        "tertiary-fixed-dim": "#ffb4a4",
        "surface-container": "#eeeeee",
        "on-background": "#1a1c1c",
        "tertiary-fixed": "#ffdad3",
        background: "#f9f9f9",
        "secondary-fixed": "#e4e2e1",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c8c6c6",
        error: "#ba1a1a",
        "surface-container-high": "#e8e8e8",
        "on-secondary-fixed": "#1b1c1c",
        "on-surface": "#1a1c1c",
        "inverse-primary": "#ffb694",
        "outline-variant": "#e2bfb0",
        secondary: "#5f5e5e",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadada",
        surface: "#f9f9f9",
        "on-error-container": "#93000a",
        "on-surface-variant": "#5a4136",
        "on-tertiary-fixed": "#3e0500",
        "primary-container": "#ff6a00",
        "primary-fixed": "#ffdbcc",
        "surface-bright": "#f9f9f9",
        outline: "#8e7164",
        "inverse-on-surface": "#f1f1f1",
        "on-primary-fixed-variant": "#7b2f00",
        "primary-fixed-dim": "#ffb694",
        "on-secondary-container": "#656464",
        "surface-container-highest": "#e2e2e2",
        "tertiary-container": "#ff6849",
        "surface-variant": "#e2e2e2",
        "on-secondary-fixed-variant": "#474747",
        "on-error": "#ffffff",
        tertiary: "#b82100",
        "on-primary-container": "#571f00",
        "on-primary": "#ffffff",
        "surface-tint": "#a14000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        none: "0px",
        soft: "2px",
        base: "4px",
        rounded: "8px",
        lg: "0.5rem",
        xl: "0.75rem",
        large: "16px",
        circle: "9999px",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "8px",
        "margin-mobile": "12px",
        "card-padding": "10px",
        unit: "4px",
        "section-gap": "24px",
      },
      maxWidth: {
        "8xl": "100rem",
      },
      screens: {
        "2xsmall": "320px",
        xsmall: "512px",
        md: "768px",
        small: "1024px",
        medium: "1280px",
        large: "1440px",
        xlarge: "1680px",
        "2xlarge": "1920px",
      },
      fontSize: {
        "3xl": "2rem",
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "price-lg": ["20px", { lineHeight: "24px", fontWeight: "800" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "500" }],
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "700" }],
      },
      fontFamily: {
        sans: [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Ubuntu",
          "sans-serif",
        ],
        "body-md": ["Hanken Grotesk"],
        "price-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "label-sm": ["Inter"],
        "label-bold": ["Inter"],
        "display-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
      },
      keyframes: {
        ring: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "fade-in-right": {
          "0%": {
            opacity: "0",
            transform: "translateX(10px)",
          },
          "100%": {
            opacity: "1",
            transform: "translateX(0)",
          },
        },
        "fade-in-top": {
          "0%": {
            opacity: "0",
            transform: "translateY(-10px)",
          },
          "100%": {
            opacity: "1",
            transform: "translateY(0)",
          },
        },
        "fade-out-top": {
          "0%": {
            height: "100%",
          },
          "99%": {
            height: "0",
          },
          "100%": {
            visibility: "hidden",
          },
        },
        "accordion-slide-up": {
          "0%": {
            height: "var(--radix-accordion-content-height)",
            opacity: "1",
          },
          "100%": {
            height: "0",
            opacity: "0",
          },
        },
        "accordion-slide-down": {
          "0%": {
            "min-height": "0",
            "max-height": "0",
            opacity: "0",
          },
          "100%": {
            "min-height": "var(--radix-accordion-content-height)",
            "max-height": "none",
            opacity: "1",
          },
        },
        enter: {
          "0%": { transform: "scale(0.9)", opacity: 0 },
          "100%": { transform: "scale(1)", opacity: 1 },
        },
        leave: {
          "0%": { transform: "scale(1)", opacity: 1 },
          "100%": { transform: "scale(0.9)", opacity: 0 },
        },
        "slide-in": {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(0)" },
        },
      },
      animation: {
        ring: "ring 2.2s cubic-bezier(0.5, 0, 0.5, 1) infinite",
        "fade-in-right":
          "fade-in-right 0.3s cubic-bezier(0.5, 0, 0.5, 1) forwards",
        "fade-in-top": "fade-in-top 0.2s cubic-bezier(0.5, 0, 0.5, 1) forwards",
        "fade-out-top":
          "fade-out-top 0.2s cubic-bezier(0.5, 0, 0.5, 1) forwards",
        "accordion-open":
          "accordion-slide-down 300ms cubic-bezier(0.87, 0, 0.13, 1) forwards",
        "accordion-close":
          "accordion-slide-up 300ms cubic-bezier(0.87, 0, 0.13, 1) forwards",
        enter: "enter 200ms ease-out",
        "slide-in": "slide-in 1.2s cubic-bezier(.41,.73,.51,1.02)",
        leave: "leave 150ms ease-in forwards",
      },
    },
  },
  plugins: [require("tailwindcss-radix")()],
}